# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:
{
  name = "super_status";
  version = "0.1.0";
  fingerprint = "0xb6e3e1a57ee81709";
  dependencies = linkFarm "zig-packages" [
    {
      name = "12200483a589a1500a1c5f6c84e4cdac571ad6c9ac125165ede425e616d8b598624d";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/byte-units-zig/archive/4d87d8e36fe7da6142265f7e9040ed82ac1bf8a5.tar.gz";
        hash = "sha256-Dy3QLBlZyBsTjaGHL3pfC89AQ/V3xTRONuuYzn96ppg=";
      };
    }
    {
      name = "12200bb68b3a24db1b15b46d2be0156ba3c8621ec9897f2a983c3d987720ead497b5";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/clap-zig/archive/983541367ecc2ac0127c2f57f8892b9a8cbf0eaa.tar.gz";
        hash = "sha256-6UGBuK70bgm8d5Mk/bO3TsmER9+Dch9/fP75kmnDZwA=";
      };
    }
    {
      name = "122015909675c56e6d67b1b79862aa812fe55ef47045df7f9847fcca344e66e92bfe";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/memory-info-zig/archive/a282f0c50c8ef98660bc4da96ef171e6388fb68b.tar.gz";
        hash = "sha256-64V4NtsK387RX2YX0PJVQZv7A2EACajvQaBELTA5CfI=";
      };
    }
    {
      name = "12202a72a51d036f8706edd877a1610ddcdd014a9cf543f9e1de37796dd0d509bf1e";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/json-fmt-zig/archive/7ab5a2c26fe5a4467949a75dcaa37b31e277d740.tar.gz";
        hash = "sha256-kWM7+dkd7UGDmUf5HkaPR/oAC7Y8E3APbMSd05ahrHk=";
      };
    }
    {
      name = "12209829184a1ad8c99e384cc0c80350e62ebed50f423e0292798ef635af87eca5ce";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/chronic/archive/8881a7f61268e3b730a02d2ecf7126a03952cd69.tar.gz";
        hash = "sha256-EfLw54yY0JuMnne1dag9WzYq9C54fU9L8JRhi7rcnig=";
      };
    }
    {
      name = "1220a744ffdf6ea853fbe02e18f5674a6474095b60f3ac1faf5ed1caa077a8c18561";
      path = fetchzip {
        url = "https://github.com/hendriknielaender/zBench/archive/f52a6a1353407ae488ba1db4e177412b1f7c1876.tar.gz";
        hash = "sha256-MiAGZ+2GiiPRgWzMFpATgI/QU/cqa+gFAyokXFnniJQ=";
      };
    }
    {
      name = "1220b497739b6fd60f627da85862cbd0cec01f3d6b7ddaa923057a7999ecfa138704";
      path = fetchzip {
        url = "https://github.com/tiehuis/zig-regex/archive/7bc0fd777c3b92c51a94531439e5913bda24030c.tar.gz";
        hash = "sha256-ai9MFgOYKqiBzMLCikSBP40+q/uPTmWqquht9ZZC590=";
      };
    }
    {
      name = "1220bae76076dcfcc611d8e37bf98d65244a91ecdf723d59c9808e97329a84a18c41";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/cpu-info-zig/archive/30d445f1d890984a962982d079fa742e7ffe4b32.tar.gz";
        hash = "sha256-VSTa6LmwVOAMG/KV+90lNzRy59P2qBS8jV4MSvIi7UI=";
      };
    }
    {
      name = "1220c9fd8160516feb5347838132ebb94de6a6936bd35a83650861aa93cb570df78d";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/pw-sinks/archive/09a5b5aa173008c4d6d26c24303453c08875ac6e.tar.gz";
        hash = "sha256-F8NLHNeg69fLXUt510L7GsoMeAf0plYOIk0PmQSmHZg=";
      };
    }
    {
      name = "1220dcb847adc72092100e0c13c791383735f58af5835f9c20a36c610936118ddb06";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/fs-info-zig/archive/8552a2e8c0d77e1bb94080e6af52f873955a6271.tar.gz";
        hash = "sha256-9HKOjR+XTHUjPt/zxr3l3gwAK+VoxQUift1jbYzW/4c=";
      };
    }
    {
      name = "1220e27f58a1fe688c89941908422c3bc31a31b0e83f70dbcaf51b5bbcee574c5944";
      path = fetchzip {
        url = "https://codeberg.org/xvzls/power-info-zig/archive/b9eefe505a283271dabd0d9a52baf9b9720e9e4d.tar.gz";
        hash = "sha256-M2uy2jDWjDv3WfEHb9W/JcoxoFjOFfKIac/zdtpWZAE=";
      };
    }
  ];
}
